[project]
name = "babagui"
version = "0.1.0"
description = "gui extension for baba-is-auto"
requires-python = ">=3.10"
dependencies = [
    "pygame>=2.6.1",
    "pybaba",
]

[tool.uv.sources]
pybaba = { path = "../../" }
